### Login with JWT

POST https://localhost:7086/api/Account/login
Content-Type: application/json

{
  "Username": "testuser",
  "Password": "testpassword"
}

### Register User

POST https://localhost:7086/api/account/register
Content-Type: application/json

{
"alias": "testuser",
"name": "Test User",
"email": "testuser@example.com",
"password": "testpassword"
}