### GET 

GET http://localhost:5007/api/user

### GET by alias

GET http://localhost:5007/api/user/janedoe

### PUT

PUT https://localhost:7086/api/user
Content-Type: application/json

{
  "name": "Updated name 2",
  "alias": "janedoe",
  "description": "Updated description",
  "emailAddress": "johndoe@example.com",
  "profilePicture": null
}

### DELETE

DELETE http://localhost:5007/api/user/johndoe